zotero:
  user_id: ${oc.env:ZOTERO_ID}
  api_key: ${oc.env:ZOTERO_KEY}
  include_path: null
  ignore_path: null

source:
  arxiv:
    category: ["cs.LG", "cs.CV"]
    include_cross_list: false
  biorxiv:
    category: null
  medrxiv:
    category: null
  chemrxiv:
    include_new_versions: false

email:
  sender: ${oc.env:SENDER}
  receiver: ${oc.env:RECEIVER}
  smtp_server: smtp.qq.com
  smtp_port: 465
  sender_password: ${oc.env:SENDER_PASSWORD}

llm:
  api:
    key: ${oc.env:OPENAI_API_KEY}
    base_url: "https://api.deepseek.com"  # 直接写死，不再用环境变量
  api_mode: chat_completion
  generation_kwargs:
    max_tokens: 16384
    model: deepseek-chat
  language: Chinese

reranker:
  local:
    model: jinaai/jina-embeddings-v5-text-nano-retrieval
    encode_kwargs:
      task: retrieval
      prompt_name: document
  api:
    key: null
    base_url: null
    model: null
    batch_size: null

executor:
  debug: false
  send_empty: true
  max_paper_num: 10
  source: ['arxiv']
  reranker: local
